### PR TITLE
Get rid of censored data

### PR DESCRIPTION
**Pull request by ldecicco-USGS**

### CODE REVIEW

**Comment by ldecicco-USGS** [comment]
@limnoliver feel free to merge this if you think it looks OK, you'll need to add the file "GLRISPSites2016.rds" to your "raw" folder. Steve sent it earlier (today?)

**Comment by limnoliver** [comment]
The censored function sets the concentrations to zero - does the file change solve the neonic-specific censoring issues?

**Comment by ldecicco-USGS** [comment]
That's what we did in the current toxEval workflow (for wastewater). I just forgot to add it to this workflow. I don't know exactly what you mean about "solve the neonic-specific censoring issues"

**Comment by limnoliver** [comment]
Sorry - the issues that I emailed about earlier: _I went back to filter out censored concentration values. When I did so, the neonic sites left for EAR and concentration weren't the same (neonics were the only class that didn't have the same N values for EAR and concentration). That is, EAR values weren't censored when the same corresponding concentration was. Steve thinks this is just an issue perhaps due to neonics coming from a different lab, and maybe the MDLs were documented slightly different? This is supported by the fact that the values for EARs where concentrations are censored are all the same across sites._ 

Or does this solve the issue upstream or EAR calculation?

**Comment by ldecicco-USGS** [comment]
I think so

**Review by limnoliver — APPROVED** [review]

**Comment by limnoliver** [comment]
@ldecicco-USGS apparently I don't have merge permission.

**Pull request merged**
